CREATE TABLE BOOKSHOP(
	SHOP_ID NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(40),
	TOTAL_NUMBER_OF_BOOKS NUMBER(4),
	TOTAL_NUMBER_OF_SOLD_BOOKS NUMBER(4),
	PASSWORD VARCHAR2(50)
);

CREATE TABLE AUTHOR(
	AUTHOR_ID NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(50),
	TOTAL_NO_BOOKS NUMBER(5),
	AUTHOR_RATING NUMBER(4),
	AWARDS VARCHAR2(100)
);

CREATE TABLE CUSTOMER(
	USER_ID NUMBER(4) PRIMARY KEY,
	NAME VARCHAR2(30),
	PASSWORD VARCHAR2(20),
	EMAIL VARCHAR2(30)
);

CREATE TABLE BUYABLE_BOOKS(
	BOOK_ID NUMBER(6) PRIMARY KEY,
	NAME VARCHAR2(33),
	ISBN NUMBER(12),
	GENRE VARCHAR2(30),
	RATING NUMBER(4),
	LOCKED VARCHAR2(30),
	CURRENT_NO_READERS NUMBER(5),
	AUTHOR_ID NUMBER(5) REFERENCES AUTHOR(AUTHOR_ID) ON DELETE CASCADE
);

CREATE TABLE CONTAINS_BUYABLE(
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	BOOK_ID NUMBER(6) REFERENCES BUYABLE_BOOKS(BOOK_ID) ON DELETE CASCADE,
	NUMBER_OF_COPIES NUMBER(6),
	SELLING_PRICE NUMBER(5)
);

CREATE TABLE PAYMENT(
	TRANSACTION_ID VARCHAR2(50) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	AMOUNT NUMBER(5),
	METHOD VARCHAR2(50)
);


CREATE TABLE SUBSCRIPTION(
	SUBSCRIPTION_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	TRANSACTION_ID VARCHAR2(50) REFERENCES PAYMENT(TRANSACTION_ID) ON DELETE CASCADE,
	SUBSCRIPTION_TYPE VARCHAR2(30),
	START_TIME DATE,
	END_TIME DATE
);

CREATE TABLE BORROWABLE_BOOKS(
	BOOK_ID NUMBER(6) PRIMARY KEY,
	NAME VARCHAR2(33),
	ISBN NUMBER(12),
	GENRE VARCHAR2(30),
	RATING NUMBER(4),
	LOCKED VARCHAR2(30),
	BORROW_TIME_LIMIT NUMBER(4), 
	CURRENT_NO_READERS NUMBER(5),
	AUTHOR_ID NUMBER(5) REFERENCES AUTHOR(AUTHOR_ID) ON DELETE CASCADE
);

CREATE TABLE BORROW(
	BORROW_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	BOOK_ID NUMBER(6) REFERENCES BORROWABLE_BOOKS(BOOK_ID) ON DELETE CASCADE,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	START_TIME DATE,
	RETURN_TIME DATE,
	LATE_FEE NUMBER(5)
);

CREATE TABLE GIFT_CARD(
	CARD_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	CARD_LEVEL NUMBER(4)
);

CREATE TABLE CART(
	CART_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	TOTAL_NO_BOOKS NUMBER(5),
	TOTAL_COST NUMBER(5),
	TOTAL_NO_BOUGHT_BOOKS NUMBER(5)
);

CREATE TABLE CART_BOOKS(
	CART_ID NUMBER(5),
	BOOK_ID NUMBER(6) REFERENCES BUYABLE_SHOP_BOOKS(SHOP_BOOK_ID) ON DELETE CASCADE
);

CREATE TABLE PURCHASE(
	PURCHASE_ID NUMBER(5) PRIMARY KEY,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	BOOK_ID NUMBER(6) REFERENCES BUYABLE_BOOKS(BOOK_ID) ON DELETE CASCADE, 
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	CARD_ID NUMBER(5) REFERENCES GIFT_CARD(CARD_ID) ON DELETE CASCADE,
	TRASACTION_ID VARCHAR2(50) REFERENCES PAYMENT(TRANSACTION_ID) ON DELETE CASCADE,
	NUMBER_OF_COPIES NUMBER(5),
	DISCOUNT NUMBER(5),
	PURCHASE_DATE DATE,
	FINAL_AMOUNT NUMBER(5)
);

CREATE TABLE EXCHANGE(
	EXCHANGE_ID NUMBER(5) PRIMARY KEY,
	EXCHANGED_BOOK_ID NUMBER(6),
	RETURNED_BOOK_ID NUMBER(6) REFERENCES BUYABLE_BOOKS(BOOK_ID) ON DELETE CASCADE,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	EXCHANGED_BOOK_BUYING_PRICE NUMBER(5),
	EXCHANGED_BOOK_SELLING_PRICE NUMBER(5),
	RETURNED_BOOK_PRICE NUMBER(5)
);

CREATE TABLE READS(
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID),
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	BOOK_ID NUMBER(6) REFERENCES BUYABLE_BOOKS(BOOK_ID) ON DELETE CASCADE, 
	CURRENTLY_READING VARCHAR2(30),
	FINISHED_READING VARCHAR2(30)
);

CREATE TABLE PUBLISHER(
	PUBLISHER_ID NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(50),
	EMAIL VARCHAR2(50),
	PASSWORD VARCHAR2(50),
	PUBLISHED_BOOK_NO NUMBER(5)
);

CREATE TABLE PUBLISHED_BOOKS(
	BOOK_ID NUMBER(6) PRIMARY KEY,
	PUBLISHER_ID NUMBER(5) REFERENCES PUBLISHER(PUBLISHER_ID),
	NAME VARCHAR2(33),
	ISBN NUMBER(12),
	GENRE VARCHAR2(30),
	RATING NUMBER(4),
	LOCKED VARCHAR2(30),
	COPIES_PUBLISHED NUMBER(6),
	CURRENT_NO_READERS NUMBER(5),
	AUTHOR_ID NUMBER(5) REFERENCES AUTHOR(AUTHOR_ID) ON DELETE CASCADE
);

ALTER TABLE PUBLISHED_BOOKS
DROP COLUMN CURRENT_NO_READERS;

ALTER TABLE BUYABLE_BOOKS
DROP (
	NAME,
	ISBN,
	GENRE,
	RATING,
	LOCKED,AUTHOR_ID);
	
ALTER TABLE BUYABLE_BOOKS
ADD SHOP_ID REFERENCES BOOKSHOP(SHOP_ID);

ALTER TABLE BUYABLE_BOOKS
ADD PUBLISHED_BOOK_ID NUMBER(5);

ALTER TABLE BUYABLE_BOOKS
ADD FOREIGN KEY(PUBLISHED_BOOK_ID) REFERENCES PUBLISHED_BOOKS(BOOK_ID);

DROP TABLE CONTAINS_BUYABLE;

ALTER TABLE BUYABLE_BOOKS
RENAME COLUMN BOOK_ID TO SHOP_BOOK_ID;

ALTER TABLE BUYABLE_BOOKS
RENAME COLUMN PRICE TO SELLING_PRICE;

ALTER TABLE BUYABLE_BOOKS RENAME TO BUYABLE_SHOP_BOOKS;

ALTER TABLE BORROWABLE_BOOKS
DROP (
	NAME,
	ISBN,
	GENRE,
	RATING,
	LOCKED,AUTHOR_ID);
	
ALTER TABLE BORROWABLE_BOOKS
ADD SHOP_ID REFERENCES BOOKSHOP(SHOP_ID);

ALTER TABLE BORROWABLE_BOOKS
ADD PUBLISHED_BOOK_ID NUMBER(5);

ALTER TABLE BORROWABLE_BOOKS
ADD FOREIGN KEY(PUBLISHED_BOOK_ID) REFERENCES PUBLISHED_BOOKS(BOOK_ID);

ALTER TABLE BORROWABLE_BOOKS
RENAME COLUMN BOOK_ID TO SHOP_BOOK_ID;

ALTER TABLE BORROWABLE_BOOKS RENAME TO BORROWABLE_SHOP_BOOKS;
ALTER TABLE READS RENAME TO READS_BUYABLE;

CREATE TABLE READS_BORROWABLE(
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID),
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	BOOK_ID NUMBER(6) REFERENCES BORROWABLE_SHOP_BOOKS(SHOP_BOOK_ID) ON DELETE CASCADE, 
	CURRENTLY_READING VARCHAR2(30),
	FINISHED_READING VARCHAR2(30)
);

CREATE TABLE CART(
	CART_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
	SHOP_ID NUMBER(5) REFERENCES BOOKSHOP(SHOP_ID) ON DELETE CASCADE,
	TOTAL_COST NUMBER(5),
	DISCOUNT NUMBER(5),
	CARD_ID NUMBER(5) REFERENCES GIFT_CARD(CARD_ID) ON DELETE CASCADE,
	TRANSACTION_ID VARCHAR2(50) REFERENCES PAYMENT(TRANSACTION_ID) ON DELETE CASCADE 
);

ALTER TABLE CART_BOOKS
ADD FOREIGN KEY(CART_ID) REFERENCES CART(CART_ID);

ALTER TABLE CART_BOOKS
ADD NUMBER_OF_COPIES NUMBER(5);

ALTER TABLE PURCHASE
DROP (CARD_ID, DISCOUNT, PURCHASE_DATE, FINAL_AMOUNT, TRASACTION_ID);

ALTER TABLE PURCHASE
ADD PRICE_AFTER_DISCOUNT NUMBER(5);

ALTER TABLE CART
ADD TOTAL_NO_BOOKS NUMBER(5);

ALTER TABLE BUYABLE_SHOP_BOOKS
ADD NUMBER_OF_COPIES NUMBER(5);

ALTER TABLE PURCHASE
RENAME COLUMN PRICE_AFTER_DISCOUNT TO PRICE;

ALTER TABLE EXCHANGE
ADD USER_ID REFERENCES CUSTOMER(USER_ID);


ALTER TABLE EXCHANGE
RENAME COLUMN EXCHANGED_BOOK_BUYING_PRICE TO OFFERED_BOOK_BUYING_PRICE;

ALTER TABLE EXCHANGE
RENAME COLUMN EXCHANGED_BOOK_SELLING_PRICE TO OFFERED_BOOK_SELLING_PRICE;

ALTER TABLE EXCHANGE
RENAME COLUMN RETURNED_BOOK_PRICE TO OFFERED_BOOK_REAL_PRICE;

ALTER TABLE EXCHANGE
ADD EXCHANGED_BOOK_PRICE NUMBER(5);

ALTER TABLE EXCHANGE
ADD PROFIT NUMBER(5);

ALTER TABLE EXCHANGE
ADD STATUS VARCHAR2(50);

UPDATE EXCHANGE SET STATUS ='Accepted' WHERE EXCHANGE_ID = 1;


DELETE FROM SHOP_BOOK_REVIEW;

SELECT COUNT(*) FROM SHOP_BOOK_REVIEW WHERE REVIEW_BODY IS NULL;

SELECT COUNT(*) FROM SHOP_BOOK_REVIEW;

ALTER TABLE BUYABLE_SHOP_BOOKS
DROP COLUMN CURRENT_NO_READERS;

ALTER TABLE PUBLISHED_BOOKS
ADD CURRENT_NO_READERS NUMBER(5);

UPDATE PUBLISHED_BOOKS
SET CURRENT_NO_READERS = 0;

ALTER TABLE EXCHANGE
DROP COLUMN RETURNED_BOOK_ID;

ALTER TABLE EXCHANGE
ADD RETURNED_BOOK_ID NUMBER(6) REFERENCES PUBLISHED_BOOKS(BOOK_ID);

CREATE TABLE SUCCESSFUL_EXCHANGE(
	SE_ID NUMBER(4) PRIMARY KEY,
	USER_ID NUMBER(4),
	OFFERED_BOOK_ID NUMBER(6) REFERENCES PUBLISHED_BOOKS(BOOK_ID) ON DELETE CASCADE,
	EXCHANGED_BOOK_ID NUMBER(6) REFERENCES BUYABLE_SHOP_BOOKS(SHOP_BOOK_ID) ON DELETE CASCADE
);

CREATE TABLE LIBRARY(
	LIBRARY_ID NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(50),
	TOTAL_NO_BOOKS NUMBER(5),
	PASSWORD VARCHAR2(50)
);

CREATE TABLE LIBRARY_MEMBERSHIP(
	USER_ID NUMBER(5) REFERENCES CUSTOMER(USER_ID),
	LIBRARY_ID NUMBER(5) REFERENCES LIBRARY(LIBRARY_ID)
);

ALTER TABLE BORROWABLE_SHOP_BOOKS
RENAME COLUMN SHOP_ID TO LIBRARY_ID;

ALTER TABLE BORROWABLE_SHOP_BOOKS
RENAME COLUMN SHOP_BOOK_ID TO LIBRARY_BOOK_ID;

CREATE TABLE LIBRARY_CARD(
	CARD_ID NUMBER(5) PRIMARY KEY,
	USER_ID NUMBER(5) REFERENCES CUSTOMER(USER_ID),
	LIBRARY_ID NUMBER(5) REFERENCES LIBRARY(LIBRARY_ID),
	CARD_LEVEL NUMBER(5)
);

ALTER TABLE BORROW
DROP COLUMN LATE_FEE;

ALTER TABLE BORROW 
ADD LATE_FEE NUMBER(5);

ALTER TABLE BORROW
ADD CARD_ID NUMBER(5) REFERENCES LIBRARY_CARD(CARD_ID);

ALTER TABLE LIBRARY_CARD
ADD BORROW_DAY_LIMIT NUMBER(5);

ALTER TABLE LIBRARY_CARD
ADD BORROW_NUM_LIMIT NUMBER(5);

ALTER TABLE BORROWABLE_SHOP_BOOKS RENAME TO BORROWABLE_LIBRARY_BOOKS;

ALTER TABLE LIBRARY_MEMBERSHIP
RENAME TO MEMBERSHIP_APPLICATION;

ALTER TABLE MEMBERSHIP_APPLICATION
ADD STATUS VARCHAR2(50);

ALTER TABLE BORROW
RENAME COLUMN SHOP_ID TO LIBRARY_ID;

ALTER TABLE BORROWABLE_LIBRARY_BOOKS
ADD STATUS VARCHAR2(50);
	
UPDATE BORROWABLE_LIBRARY_BOOKS
SET STATUS = 'Available';

ALTER TABLE BORROWABLE_LIBRARY_BOOKS
DROP COLUMN BORROW_TIME_LIMIT;

CREATE TABLE SHOP_BOOK_REVIEW(
	REVIEW_ID NUMBER(5) PRIMARY KEY,
	REVIEW_BODY VARCHAR2(1000),
	SHOP_BOOK_ID NUMBER(5) REFERENCES BUYABLE_SHOP_BOOKS(SHOP_BOOK_ID),
	USER_ID NUMBER(5) REFERENCES CUSTOMER(USER_ID),
	RATING NUMBER(5),
	CURRENTLY_READING VARCHAR2(50),
	FINISHED_READING VARCHAR2(50)
);

CREATE TABLE LIBRARY_BOOK_REVIEW(
	REVIEW_ID NUMBER(5) PRIMARY KEY,
	REVIEW_BODY VARCHAR2(1000),
	LIBRARY_BOOK_ID NUMBER(5) REFERENCES BORROWABLE_LIBRARY_BOOKS(LIBRARY_BOOK_ID),
	USER_ID NUMBER(5) REFERENCES CUSTOMER(USER_ID),
	RATING NUMBER(5),
	CURRENTLY_READING VARCHAR2(50),
	FINISHED_READING VARCHAR2(50)
);

DROP TABLE READS_BORROWABLE;
DROP TABLE READS_BUYABLE;

ALTER TABLE BORROWABLE_LIBRARY_BOOKS
ADD NUMBER_OF_COPIES NUMBER(5);

ALTER TABLE BORROW
ADD NUMBER_OF_COPIES NUMBER(5);

ALTER TABLE SUCCESSFUL_EXCHANGE
ADD IS_EXCHANGED NUMBER(6);

UPDATE SUCCESSFUL_EXCHANGE SET IS_EXCHANGED = 0; 

ALTER TABLE CUSTOMER
ADD FIRST_SIGN_UP DATE;

ALTER TABLE CUSTOMER
ADD USAGE_DAYS NUMBER(5);

UPDATE CUSTOMER SET FIRST_SIGN_UP = SYSDATE - 10;

ALTER TABLE CUSTOMER
RENAME COLUMN FIRST_SIGN_UP TO SIGN_UP_DATE;

ALTER TABLE BORROW
ADD DAYS_REMAINING NUMBER(5);

ALTER TABLE PURCHASE
ADD TRANSACTION_ID VARCHAR2(50) REFERENCES PAYMENT(TRANSACTION_ID);

ALTER TABLE PAYMENT
RENAME COLUMN METHOD TO PAYMENT_TYPE;

UPDATE PAYMENT SET PAYMENT_TYPE = 'PURCHASE';
ALTER TABLE PAYMENT
ADD PAYMENT_DATE DATE;


ALTER TABLE GIFT_CARD
ADD DISCOUNT_PER_LEVEL NUMBER(5);

ALTER TABLE GIFT_CARD
ADD EXCHANGE_LIMIT NUMBER(5);

ALTER TABLE LIBRARY_CARD
ADD LATE_FEE_RATE NUMBER(5);

ALTER TABLE GIFT_CARD
ADD SUBSCRIPTION_ID REFERENCES SUBSCRIPTION(SUBSCRIPTION_ID);

ALTER TABLE GIFT_CARD
DROP COLUMN EXCHANGE_LIMIT;

ALTER TABLE CUSTOMER
ADD ADDRESS VARCHAR2(50);

ALTER TABLE CUSTOMER
ADD EXCHANGE_LIMIT NUMBER(5);

DELETE FROM PURCHASE WHERE USER_ID = 2 AND SHOP_ID = 2;

CREATE TABLE USER_EXCHANGE(
U_FROM NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
U_TO NUMBER(4) REFERENCES CUSTOMER(USER_ID) ON DELETE CASCADE,
OFFERED_BOOK_ID NUMBER(6) REFERENCES PUBLISHED_BOOKS(BOOK_ID) ON DELETE CASCADE,
	EXCHANGED_BOOK_ID NUMBER(6) REFERENCES PUBLISHED_BOOKS(BOOK_ID) ON DELETE CASCADE
);

ALTER TABLE USER_EXCHANGE
ADD STATUS NUMBER (4);
ALTER TABLE USER_EXCHANGE
ADD CONDITION VARCHAR2(100);	
